branch-defaults:
  main:
    environment: sherlock-env
global:
  application_name: sherlock
  branch: null
  default_ec2_keyname: aws-eb-demo
  default_platform: Python 3.7
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
